# Generated by Django 4.2.5 on 2023-09-21 06:22

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="img/thumbs/", verbose_name="Imagem"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Nome da Música",
                    ),
                ),
                (
                    "music",
                    models.FileField(
                        upload_to="musics/", verbose_name="selecione a música"
                    ),
                ),
            ],
        ),
    ]
