# Generated by Django 4.2.5 on 2023-09-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="music",
            field=models.FileField(
                upload_to="audio/", verbose_name="selecione a música"
            ),
        ),
    ]
