# Generated by Django 4.2.5 on 2023-09-21 06:34

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_music_music"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                default="img/thumbs/default/default.jpg",
                upload_to="img/thumbs/",
                verbose_name="Imagem",
            ),
        ),
    ]
